# general settings for image SR training
name: train_WaDAIR_SR_x16
model_type: MambaIRModel
scale: 16
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: algae
    type: PairedImageDataset
    dataroot_gt: C:\Users\A\Desktop\datasets\algae_2\train\train
    dataroot_lq: C:\Users\A\Desktop\datasets\algae_2\train\train_x16
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 1024
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 500
    prefetch_mode: ~
    # pin_memory: true

  val:
    name: algae
    type: PairedImageDataset
    dataroot_gt: C:\Users\A\Desktop\datasets\algae_2\test\test
    dataroot_lq: C:\Users\A\Desktop\datasets\algae_2\test\test_x16
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: WaDAIR
  upscale: 16
  in_chans: 3
  img_range: 1.
  d_state: 16
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  ssm_ratio: 2.0
  mlp_ratio: 2.5
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

  img_size: 64
  dynamic_ids: False
  batch_size: 2
  scan_len: 8

# path
path:
  pretrain_network_g: C:\Users\A\Desktop\MaIR\experiments\train_MaIR_SR_x16_algae\models\net_g_302000.pth
  strict_load_g: false
  resume_state: C:\Users\A\Desktop\MaIR\experiments\train_MaIR_SR_x16_algae\training_states\302000.state

# training settings, we finetune the pretrained X2 model for 250k iterations to save computing resources following previous settings
train:
  optim_g:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 150000, 175000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  # val_freq and val_freq_final is used for trainF.py, where first 400000 iters we only validate model every 25k iters, after that we validate every 5k iters
  # It is mainly because that the training is not stable at the beginning, and validation is also time consuming since IO speed of our GPU is not enough.
  # So we validate less frequently at the beginning.
  val_freq: 2000
  val_freq_final: 2000
  val_milestone: 200000 

  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 16
      test_y_channel: true
    ssim: 
      type: calculate_ssim
      crop_border: 16
      test_y_channel: true

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: 2000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
# dist_params:
#   backend: nccl
#   port: 29500